---
name: Wheel Builds
on:
  push:
    branches:
      - 'stable/0.17'
jobs:
  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -U setuptools-rust
      - name: Build sdist
        run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*
          name: sdist-rustworkx
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  retworkx-compat-build:
    name: Build retworkx
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -U setuptools-rust wheel build
      - name: Build sdist
        run: pushd retworkx && python setup.py bdist_wheel && popd
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*
          name: sdist-retworkx
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
